### ISSUE TITLE
2024-01-18 Dvergsignal feil høyde i forhold til SOK

### ISSUE THREAD

**Issue by eihov** [Railcomplete-AS/RailCOMPLETE-DNA-NO-BN#188]
- [ ] Dvergsignal kan ende opp i feil høyde i forhold til SOK med DNA 2021.a. Høyden på nærmeste lampe skal være minst 1.5 meter over SOK

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/71493864/92c4beb4-d2f4-4b86-a6aa-2bc24b702e55)

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/71493864/d6c88bf8-31ea-41b3-a23f-e2f725dd2590)

**Comment by clfey** [comment]
Pass på - Bane NOR har ofte inkonsistente regler. 

Det finnes en konstruksjonstegning - som vi har brukt - som angi tre varianter av dvergsignalmast-med-tverrjern-nedi-pukken. Disse mastene er hhva 1600, 2000 eller 3000 mm lange, som Ø76 galvanisert stålrør. Det står i konstruksjonstegningen at 900mm skal befinne seg under SOK, resten er over SOK. Deretter skal dvergsignalhodet plasseres oppå masten, som da blir innfestingspunkt på hhv 700, 1100 eller 2100 mm over SOK. Det gir høyde på senter laveste lanterne på hhv 0.75 eller 1.15 eller 2.15 over SOK. Se illustrasjon:

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/8375198/bccb3a2d-9ca7-42d6-af75-66ca8fe315c5)

**Comment by clfey** [comment]
Jeg ringte Vojana og viste henne at hun både har 3000-mm standard Ds-stolpe i 3D-biblioteket (det gir nedre lanterner i høyde 2,150 over SOK), og viste hvordan hun kan "skru det sammen" fra Ds-hode med Pole Routing, og legge til fundament og koblingsboks for Ø76 stolpe. Da ser det slik ut:

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/8375198/dc0e61be-6f6e-4c43-b147-d374b2554fd9)
