### ISSUE TITLE
2024-01-30 check formulas on E101

### ISSUE THREAD

**Issue by khhelland** [Railcomplete-AS/RailCOMPLETE-DNA-NO-BN#208]
Formler på skilt E101: Er de riktige?

**Comment by svknoe** [comment]
I've investigated all the Lua formulas on the `JBTSA_MSS ERTMS ID board object type`. They all seem correct, with the following exception:

![image](https://github.com/Railcomplete-AS/RailCOMPLETE-DNA-NO-BN/assets/33001939/991e41f1-bbd9-44b4-a806-67a4af2c13c2)

Here there's a mismatch between is text and the code. Is the code supposed to be switched, as indicated in the image above?

@clfey Is the text correct or is the code correct (or neither)?

**Comment by clfey** [comment]
Should prbably be

`Attachment and Attachment.code or ""`

But I wonder why the formula was not in order, it is just a very small one.

**Comment by svknoe** [comment]
f0a8e61bfa8a22607849621b61d66e2fb8f58041

Fixed above bug. In my opinion the E101 Lua formulas are now correct.
