### ISSUE TITLE
2024-03-20 ETCS translations

### ISSUE THREAD

**Issue by svknoe** [Railcomplete-AS/RailCOMPLETE-DNA-NO-BN#226]
Our ETCS signals have sloppy use of language. Some are in English and some are in Norwegian. In particular, the variants for `JBTSA_MSS ERTMS Signalskilt`and `JBTSA_MSS ERTMS Signalskilt` are in English, while `JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt` variants are in Norwegian.

- [x] Translate all ETCS names and variants to English.
- [ ] ~~Give all ETCS names and variants Norwegian display names~~

**Comment by svknoe** [comment]
There doesn't seem to be a mechanism for display names on variants, so I suggest that we stick to either all English ERTMS names or all Norwegian ones, and then maybe add display names later.

**Comment by clfey** [comment]
English now - make issue to add Displayname & description to Variants.

**Comment by svknoe** [comment]
Prior to the below work we should remove dwarf signals from `JBTSA_ERT ERTMS-signal`.

Question: Why are ERTMS stop signal boards in `JBTSA_ERT ERTMS-signal` and all other non-ID ERTMS boards in `JBTSA_MSS ERTMS Signalskilt`?

That distinction doesn't make any sense to me. The name `JBTSA_ERT ERTMS-signal` conveys that its category is about _all_ ERTMS signals, but somehow ID signals, dwarf signals and stop signals are not included. It seems natural that `JBTSA_MSS ERTMS Signalskilt` is a subtype of `JBTSA_ERT ERTMS-signal`, going from the language alone.

# Suggested names changes
## Object types
- `JBTSA_MSS ERTMS Signalskilt` -> `JBTSA_MSS ERTMS Other board`
- `JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt` -> `JBTSA_MSS ERTMS ID board`
- `JBTSA_ERT ERTMS-signal` -> `JBTSA_ERT ERTMS Marker board`
  - -> `JBTSA_SIG ERTMS Shunting signal`

## Variants
### JBTSA_MSS ERTMS Signalskilt
No changes, variants are already in Englisg, e.g. `E106 Stop for shunting`. I think that all our ERTMS signal boards should match this pattern.

### JBTSA_MSS Signal E101 ERTMS Identifikasjonsskilt

1. `Signal E101-A ID-skilt, Indre, 400x325, hvit` -> `E101-A ID board, intermediate stop sign, 400x325, white`
2. `Signal E101-B ID-skilt, Innkjør, 400x325, gul` -> `E101-B ID board, entry stop sign, 400x325, yellow`
3. `Signal E101-C ID-skilt, Utkjør, Ø400, gul` -> `E101-C ID board, exit stop sign, Ø400, yellow`
4. `Signal E101-D ID-skilt, Blokk, Ø400, hvit` -> `E101-D ID board, blocking stop sign, Ø400, white`
5. `Signal E101-E ID-skilt, Dverg, 160x150` -> `E101-E ID board, shunting, 160x150`
6. `Signal E101-F ID-skilt, Dverg på bakken under MB i åk, 160x150` -> To be removed. Only lone shunting signals have ID signs. Let F remain unused.
7. `Signal E101-G ID-skilt, Stopp for skift, 400x325` -> `E101-G ID board, stop for shunting, 400x325`
8. `Signal E101-H ID-skilt, Forriglet område, 400x325` -> `E101-H ID board, interlocked area, 400x325`
9. `Signal E101-J ID-skilt, Veisikringsanlegg, 400x325` -> `E101-J ID board, level crossing, 400x325`
10. `Signal E101-K ID-skilt, Snøskredområde, 400x325` -> `E101-K ID board, avalanche area, 400x325`
11. `Signal E101-L ID-skilt, Frostport, 400x325` -> `E101-L ID board, frost gate, 400x325`

I am particularly interested in feedback on the following translations:
- Capitalisation
- Indre -> intermediate stop sign
- Innkjør -> entry
- Utkjør -> exit
- Ø400 -> Ø400
- Dverg -> shunting
- Dverg på bakken under MB i åk -> shunting on the ground under portal mounted MB
- Veisikringsanlegg -> level crossing

### JBTSA_ERT ERTMS-signal
12. `ERTMS E35 Stoppskilt, sidestilt` -> `E35 Stop sign, side of track`
13. `ERTMS E35 Stoppskilt, sidestilt med dverg` -> To be removed.
14. `ERTMS E35 Stoppskilt, sidestilt med dverg` -> To be removed.
15. `ERTMS E35 Stoppskilt, sidestilt med lav dverg` -> To be removed.
16. `ERTMS E35 Stoppskilt, over sporet` -> `E35 Stop sign, above track`
17. `ERTMS E35 Stoppskilt, over sporet med dverg` -> To be removed.
18. `ERTMS dverg` -> To be removed.

**Comment by svknoe** [comment]
a88bfd13da7374519e4e907ada9d2103ef13249b

Postponed translations of shunting signals because they are getting split into their own object type.
